version: '3'

services:
  usuarios_vehiculos:
    build: UsuariosVehiculos
    ports:
      - "8080:8080"
    environment:
      DB_URL_PROD: jdbc:mysql://parking_app:3306/usta_parking?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME_PROD: root
      DB_PASSWORD_PROD: root
    restart: always
    depends_on:
      parking_app:
          condition: service_healthy
  parking_app:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: usta_parking
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10